---
abstract: 'Support for hierarchical exception classes'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Hierarchy
provides:
  Error::Hierarchy:
    file: lib/Error/Hierarchy.pm
    version: 1.101690
  Error::Hierarchy::Base:
    file: lib/Error/Hierarchy/Base.pm
    version: 1.101690
  Error::Hierarchy::Container:
    file: lib/Error/Hierarchy/Container.pm
    version: 1.101690
  Error::Hierarchy::Internal:
    file: lib/Error/Hierarchy/Internal.pm
    version: 1.101690
  Error::Hierarchy::Internal::AbstractMethod:
    file: lib/Error/Hierarchy/Internal/AbstractMethod.pm
    version: 1.101690
  Error::Hierarchy::Internal::Class:
    file: lib/Error/Hierarchy/Internal/Class.pm
    version: 1.101690
  Error::Hierarchy::Internal::CustomMessage:
    file: lib/Error/Hierarchy/Internal/CustomMessage.pm
    version: 1.101690
  Error::Hierarchy::Internal::DBI:
    file: lib/Error/Hierarchy/Internal/DBI.pm
    version: 1.101690
  Error::Hierarchy::Internal::DBI::DBH:
    file: lib/Error/Hierarchy/Internal/DBI/DBH.pm
    version: 1.101690
  Error::Hierarchy::Internal::DBI::DRH:
    file: lib/Error/Hierarchy/Internal/DBI/DRH.pm
    version: 1.101690
  Error::Hierarchy::Internal::DBI::H:
    file: lib/Error/Hierarchy/Internal/DBI/H.pm
    version: 1.101690
  Error::Hierarchy::Internal::DBI::STH:
    file: lib/Error/Hierarchy/Internal/DBI/STH.pm
    version: 1.101690
  Error::Hierarchy::Internal::DBI::Unknown:
    file: lib/Error/Hierarchy/Internal/DBI/Unknown.pm
    version: 1.101690
  Error::Hierarchy::Internal::EmptyArrayRef:
    file: lib/Error/Hierarchy/Internal/EmptyArrayRef.pm
    version: 1.101690
  Error::Hierarchy::Internal::EmptyHashRef:
    file: lib/Error/Hierarchy/Internal/EmptyHashRef.pm
    version: 1.101690
  Error::Hierarchy::Internal::NoArrayRef:
    file: lib/Error/Hierarchy/Internal/NoArrayRef.pm
    version: 1.101690
  Error::Hierarchy::Internal::NoHashRef:
    file: lib/Error/Hierarchy/Internal/NoHashRef.pm
    version: 1.101690
  Error::Hierarchy::Internal::ReadOnlyAttribute:
    file: lib/Error/Hierarchy/Internal/ReadOnlyAttribute.pm
    version: 1.101690
  Error::Hierarchy::Internal::ValueUndefined:
    file: lib/Error/Hierarchy/Internal/ValueUndefined.pm
    version: 1.101690
  Error::Hierarchy::Mixin:
    file: lib/Error/Hierarchy/Mixin.pm
    version: 1.101690
  Error::Hierarchy::Test:
    file: lib/Error/Hierarchy/Test.pm
    version: 1.101690
  Error::Hierarchy::Util:
    file: lib/Error/Hierarchy/Util.pm
    version: 1.101690
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Accessor::Complex: 0
  Data::Container: 0
  Data::Dumper: 0
  Data::Inherited: 0
  Data::Miscellany: 0
  Data::UUID: 0
  Error: 0
  Exporter: 0
  Sys::Hostname: 0
  Test::Builder: 0
  Test::Exception: 0
  YAML: 0
  constant: 0
  overload: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Error-Hierarchy
  homepage: http://search.cpan.org/dist/Error-Hierarchy/
  repository: http://github.com/hanekomu/Error-Hierarchy
version: 1.101690
