--- 
abstract: support for hierarchical exception classes
author: Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Error-Hierarchy
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Complex: 0
  Data::Container: 0
  Data::Inherited: 0
  Data::Miscellany: 0
  Data::UUID: 0
  Error: 0
  Sys::Hostname: 0
  Test::Exception: 0
  perl: 5.6.0
version: 0.04
